// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiichiGang.Data;

namespace RiichiGang.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210526134851_SixthMigration")]
    partial class SixthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RiichiGang.Domain.Bracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("FinalScoreMultiplier")
                        .HasColumnType("float");

                    b.Property<int>("GamesPerSeries")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("NumberOfAdvancing")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeries")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("WinCondition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Brackets");
                });

            modelBuilder.Entity("RiichiGang.Domain.BracketPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BracketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<float>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BracketId");

                    b.HasIndex("PlayerId");

                    b.ToTable("BracketPlayers");
                });

            modelBuilder.Entity("RiichiGang.Domain.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Localization")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("RiichiGang.Domain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BracketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("EndScoreNan")
                        .HasColumnType("float");

                    b.Property<float>("EndScorePei")
                        .HasColumnType("float");

                    b.Property<float>("EndScoreSha")
                        .HasColumnType("float");

                    b.Property<float>("EndScoreTon")
                        .HasColumnType("float");

                    b.Property<string>("LogFile")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MatchResultNan")
                        .HasColumnType("int");

                    b.Property<int>("MatchResultPei")
                        .HasColumnType("int");

                    b.Property<int>("MatchResultSha")
                        .HasColumnType("int");

                    b.Property<int>("MatchResultTon")
                        .HasColumnType("int");

                    b.Property<int>("NanchaId")
                        .HasColumnType("int");

                    b.Property<int>("PeichaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlayedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int>("ShachaId")
                        .HasColumnType("int");

                    b.Property<int>("TonchaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BracketId");

                    b.HasIndex("NanchaId");

                    b.HasIndex("PeichaId");

                    b.HasIndex("ShachaId");

                    b.HasIndex("TonchaId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RiichiGang.Domain.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("RiichiGang.Domain.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RiichiGang.Domain.Ruleset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AgariYame")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AkaDora")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Atozuke")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Genten")
                        .HasColumnType("int");

                    b.Property<bool>("KanDora")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("KanUraDora")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Kuikae")
                        .HasColumnType("int");

                    b.Property<bool>("Kuitan")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Mochiten")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("Oka")
                        .HasColumnType("int");

                    b.Property<bool>("TenpaiYame")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Tobi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UmaFirst")
                        .HasColumnType("int");

                    b.Property<int>("UmaFourth")
                        .HasColumnType("int");

                    b.Property<int>("UmaSecond")
                        .HasColumnType("int");

                    b.Property<int>("UmaThird")
                        .HasColumnType("int");

                    b.Property<bool>("UraDora")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Name")
                        .IsUnique();

                    b.ToTable("Rulesets");
                });

            modelBuilder.Entity("RiichiGang.Domain.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowNonMembers")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("RequirePermission")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.HasIndex("UserId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("RiichiGang.Domain.TournamentPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId");

                    b.ToTable("TournamentPlayers");
                });

            modelBuilder.Entity("RiichiGang.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RiichiGang.Domain.Bracket", b =>
                {
                    b.HasOne("RiichiGang.Domain.Tournament", "Tournament")
                        .WithMany("Brackets")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiichiGang.Domain.BracketPlayer", b =>
                {
                    b.HasOne("RiichiGang.Domain.Bracket", "Bracket")
                        .WithMany("Players")
                        .HasForeignKey("BracketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.TournamentPlayer", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiichiGang.Domain.Club", b =>
                {
                    b.HasOne("RiichiGang.Domain.User", "Owner")
                        .WithMany("OwnedClubs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiichiGang.Domain.Game", b =>
                {
                    b.HasOne("RiichiGang.Domain.Bracket", "Bracket")
                        .WithMany("Games")
                        .HasForeignKey("BracketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.BracketPlayer", "Nancha")
                        .WithMany()
                        .HasForeignKey("NanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.BracketPlayer", "Peicha")
                        .WithMany()
                        .HasForeignKey("PeichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.BracketPlayer", "Shacha")
                        .WithMany()
                        .HasForeignKey("ShachaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.BracketPlayer", "Toncha")
                        .WithMany()
                        .HasForeignKey("TonchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiichiGang.Domain.Membership", b =>
                {
                    b.HasOne("RiichiGang.Domain.Club", "Club")
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiichiGang.Domain.Notification", b =>
                {
                    b.HasOne("RiichiGang.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.HasOne("RiichiGang.Domain.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiichiGang.Domain.Ruleset", b =>
                {
                    b.HasOne("RiichiGang.Domain.Club", "Club")
                        .WithMany("Rulesets")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiichiGang.Domain.Tournament", b =>
                {
                    b.HasOne("RiichiGang.Domain.Ruleset", "Ruleset")
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.User", null)
                        .WithMany("Tournaments")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("RiichiGang.Domain.TournamentPlayer", b =>
                {
                    b.HasOne("RiichiGang.Domain.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiichiGang.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RiichiGang.Domain.User", b =>
                {
                    b.OwnsOne("RiichiGang.Domain.Stats", "Stats", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<int>("CallRounds")
                                .HasColumnType("int");

                            b1.Property<int>("DealInRounds")
                                .HasColumnType("int");

                            b1.Property<int>("FirstPlaces")
                                .HasColumnType("int");

                            b1.Property<int>("FourthPlaces")
                                .HasColumnType("int");

                            b1.Property<int>("RiichiRounds")
                                .HasColumnType("int");

                            b1.Property<int>("SecondPlaces")
                                .HasColumnType("int");

                            b1.Property<int>("ThirdPlaces")
                                .HasColumnType("int");

                            b1.Property<int>("TotalBusted")
                                .HasColumnType("int");

                            b1.Property<int>("TotalGames")
                                .HasColumnType("int");

                            b1.Property<int>("TotalRounds")
                                .HasColumnType("int");

                            b1.Property<int>("TsumoRounds")
                                .HasColumnType("int");

                            b1.Property<int>("WinRounds")
                                .HasColumnType("int");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
